### ISSUE TITLE
SelectorSyntaxError if an attribute value contains a colon

### ISSUE THREAD

**Issue by nag5000** [peterbe/premailer#224]
```html
<style>
  code[data-foo="a:b"] { color: red; }
</style>

<code data-foo="a:b">asddsa</code>
```

`$ python -m premailer -f tmp.html`  --> cssselect.parser.SelectorSyntaxError: Unclosed string at 14

**Comment by peterbe** [comment]
`premailer` is (unfortunately) at the mercy of `cssselect` and it can't cope with `code[data-foo="a:b"]` there's not a whole lot we can do here. Perhaps, at best, is to document this fact in the README so that users are aware that `premailer` is a "subset" of `cssselect`'s functionality. 

Or, do you think you can take a look at `cssselect` and fix it there?

**Comment by nag5000** [comment]
Oh, yes, it's a bug in `cssselect`, not in `premailer`. It looks like `cssselect` isn't maintained (the latest commit was in Dec 2017).
